Allow fixed homeserver
Awesome-Technologies/synapse-admin pull request #142
Opened 2021-05-17 17:06 UTC by dklimpel

Fixes: #114

Add parameter  `REACT_APP_SERVER` to fix homeserver at build-time.

2021-05-18 07:19 UTC, awesome-manuel requested changes
Some minor changes requested.

2021-05-18 07:19 UTC, awesome-manuel commented on src/components/LoginPage.js
> +            disabled={override_server ? true : loading}
IMHO this is better readable:
```suggestion
            disabled={override_server || loading}
```

2021-05-18 07:19 UTC, awesome-manuel commented on src/components/LoginPage.js
> +      initialValues={{ base_url: override_server ? override_server : base_url }}
```suggestion
      initialValues={{ base_url: override_server || base_url }}
```
`||` returns the "truthy" value, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR

2021-05-18 07:19 UTC, awesome-manuel commented on src/synapse/authProvider.js
> +      : base_url;
```suggestion
    base_url = process.env.REACT_APP_SERVER || base_url;
```
See other suggestions.

2021-05-18 07:19 UTC, awesome-manuel commented on src/components/LoginPage.js
> +  const override_server = process.env.REACT_APP_SERVER;
Maybe `cfg_base_url` instead of `override_server`.

2021-05-18 10:39 UTC, awesome-manuel approved these changes

2021-05-18 10:39 UTC, merged

2021-08-31 22:54 UTC, rainer-geiger commented
Can you include something like this in your dockerfile to pass 'REACT_APP_SERVER' as arg from docker-compose.yml?

```
ARG REACT_APP_SERVER
ENV REACT_APP_SERVER $REACT_APP_SERVER
```

If I'm not completely wrong, then you should be able to user fixed homeserver from docker-compose like this:

```
build:
      [...]
      args:
        - REACT_APP_SERVER=https://matrix.yourdomain.com
```