GitHub Pages Deploy
Awesome-Technologies/synapse-admin pull request #189
Opened 2021-09-15 22:54 UTC by dfuchss

Thanks for the nice admin ui.
I just thought about deploying the latest version to GitHub Pages since that makes the application easier to test/use by admins.
Therefore, you might think about merging this PR.

You can see the actual result on the [GH Page of my Fork](https://dfuchss.github.io/synapse-admin)

2021-11-18 07:48 UTC, dklimpel requested changes

2021-11-18 07:48 UTC, dklimpel commented on .github/workflows/edge_ghpage.yml
> + push:
Your file does not pass `yarn prettier`.
These changes are result of `yarn fix`.

```suggestion
  workflow_dispatch:
  push:
```

2021-11-18 07:48 UTC, dklimpel commented on .github/workflows/edge_ghpage.yml
> +
```suggestion

```

2021-11-18 07:48 UTC, dklimpel commented on .github/workflows/edge_ghpage.yml
> +
```suggestion

```

2021-11-18 07:48 UTC, dklimpel commented on .github/workflows/edge_ghpage.yml
> +
```suggestion

```

2021-11-18 10:30 UTC, dfuchss commented
I've accepted your change requests :)

2022-01-23 18:45 UTC, dfuchss commented
Since this PR is now open approx. 4 months, I would like the maintainers what they think about the PR.

For me it would be the best to either close the PR or to merge it. I can't have a look at old open PRs and the dependencies of it might change and might need some update in the future.

2022-01-31 16:38 UTC, awesome-michael commented
Thanks for your contribution. You're right and I'm sorry that it took so long. We had some internal discussions and lost focus a bit.. 
Will merge it now.

2022-01-31 16:38 UTC, merged

2022-01-31 18:29 UTC, dfuchss commented
@awesome-michael thanks a lot for the response :)

I assume that you have to allow pushes via GH_TOKEN in the Actions Settings of the Repository.
![image](https://user-images.githubusercontent.com/22198798/151851599-47aabce3-2ee8-44cb-a26e-4b2af6b30b4e.png)

2022-01-31 18:39 UTC, awesome-michael commented
Thank you so much for looking into it.. I had no time to investigate further. Write permissions are greyed out at the moment, I'm searching right now..

2022-01-31 18:45 UTC, dfuchss commented
You can also look into the actions settings of your organization. 

Otherwise, you could use a deployment ssh key https://github.com/JamesIves/github-pages-deploy-action#using-an-ssh-deploy-key-

or create a Personal Access Token for a "Bot" User.

2022-02-17 20:04 UTC, dfuchss commented
@awesome-michael did you find the time to look at the problem in your permission settings?

2022-02-18 11:44 UTC, dklimpel commented
It seems to work now.

2022-02-18 13:22 UTC, dfuchss commented
👍 nice work , everyone can see the deployment in the list of environments :)

2022-02-18 14:15 UTC, awesome-michael commented
Think I will add the link to the readme later..
Thanks for your work!