add Persian langiage
Awesome-Technologies/synapse-admin pull request #504
Opened 2024-04-09 06:02 UTC by fateme-shm

Add new PR for Persian language

step1: add fa.js to "/src/i18n/"
step2: add package  "ra-language-farsi"  to package.json
step3: add li to "LoginPage.jsx" line 294 for select Persian langiage

2024-04-15 07:00 UTC, bret0nschiz0 commented
good idea

2024-04-16 07:01 UTC, mahtabadelnia commented
Waiting for it to happen👍

2024-04-16 07:14 UTC, ThyMYthOS requested changes

2024-04-16 07:14 UTC, ThyMYthOS commented on package.json
> -    "start": "REACT_APP_VERSION=$(git describe --tags) react-scripts start",
Please don't modify those lines

2024-04-16 12:44 UTC, merged